print("===== Desafio 04 ====")
teste = input("Digite algo: ")
print("O tipo primitivo desse valor é", type(teste))
print("Só tem espaços?", teste.isspace())
print("É um número?", teste.isnumeric())
print("É alfabético?", teste.isalpha())
print("É alfanumérico?", teste.isalnum())
