nome = input('Qual  é seu nome? ')
print('Prazer em te conhecer {:=^20}!'.format(nome))
print('Alinhando o nome na esquerda {:>20}!'.format(nome))
print('Alinhando o nome na direita {:<20}!'.format(nome))
print('Alinhando o nome no meio {:^20}!'.format(nome))
